name = "H2Frames"
uuid = "7468a3b7-930e-48c8-a27b-9d42b62f3d3e"
license = "MIT"
authors = ["Gerasimos Panou <gerasimos.panou@gmail.com>"]
description = "A Julia package for H2 matrix frames."
version = "0.2.3"

[deps]
HPACK = "03a3583f-3b84-4ec3-931d-7334ff455684"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
HPACK = {url = "https://github.com/Grasimos/HPACK.jl"}

[compat]
JuliaFormatter = "2.1.3"
Test = "1.11.0"
