name = "Http2Frames"
uuid = "7468a3b7-930e-48c8-a27b-9d42b62f3d3e"
license = "MIT"
authors = ["Gerasimos Panou <gerasimos.panou@gmail.com>"]
description = "A Julia package for H2 matrix frames."
version = "0.4.4"

[deps]
Http2Hpack = "03a3583f-3b84-4ec3-931d-7334ff455684"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Http2Hpack = "0.2"
Test = "1.11.0"
julia = "^1.11"
